//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_app_uepaticket.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class @event
    {
        public int id { get; set; }
        [Required(ErrorMessage =("*"))]
        public string name { get; set; }
        public string description { get; set; }
        [Required(ErrorMessage = ("*"))]
        public string image_url { get; set; }
        [Required(ErrorMessage = ("*"))]
        public Nullable<int> event_category_id { get; set; }
        [Required(ErrorMessage = ("*"))]
        public Nullable<int> event_location_id { get; set; }
    }
}
